# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_length',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_title',
            field=models.TextField(max_length=100),
        ),
    ]
