# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_scheduler', '0003_auto_20171030_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_length',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_title',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
